---
- name: Setup registry insecure
  hosts: localhost
  gather_facts: no
  become: yes
  tasks:
    - name: setup_hosts
      become: yes
      lineinfile:
        path: result.txt
        regexp: "jang"
        line: '"insecure-registries" : ["harbor.okestro.cld"]"'
      notify:
        - modify_hosts
        # state: absent
  handlers:
  - name: modify_hosts
    shell: touch a.txt
